In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

### yes there is a difference between data type of list_ and array_list. list_ is of list type and When we ask for the type of an NumPy object, we get the type of the container--something like numpy.ndarray. While when we ask for the dtype, we get the (numpy-managed) type of the elements.

In [3]:
print(type(list_))
print(type(array_list))
print(array_list.dtype)

<class 'list'>
<class 'numpy.ndarray'>
<U1


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list

In [3]:
# data type of each element in list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [4]:
# type of elements in Array
array_list.dtype

dtype('<U1')

# Q3. Considering the following changes in the variable, array_list:

# array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.


In [5]:
array_list = np.array(object = list_, dtype = int)

### yes there will be a difference in the data type of the elements presents in both variables.
### list_ : elements in list_ will be of string type
### array_list : elements in the array_list is of the integer type.

In [7]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
array_list.dtype

dtype('int64')

# Q4. Write a code to find the following characteristics of variable, num_array:
# (i)  shape
# (ii) size

In [9]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [11]:
print(f"the shape of the array is :{ num_array.shape}")
print(f"the size of the array is :{ num_array.size}")

the shape of the array is :(2, 3)
the size of the array is :6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [16]:
arr= np.zeros((3,3))
print(f"arrays 3*3 with zeros only \n {arr}")

arrays 3*3 with zeros only 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [15]:
arr_id5=np.eye(5)
print(f"identity matrix with shape 5X5 is \n {arr_id5}")

identity matrix with shape 5X5 is 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
